package datosApp;


/**
* datosApp/datosOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Persona.idl
* lunes 23 de abril de 2018 07:38:57 PM COT
*/

public interface datosOperations 
{
  boolean InsertarDatos (int identificacion, String nombre, String apellido1, String apellido2, String genero);
  String ConsultarDatos (int identificacion);
  boolean EliminarDatos (int identificacion);
  boolean ActualizarDatos (int identificacion, String nombre, String apellido1, String apellido2, String genero);
  String ListarDatos ();
  void shutdown ();
} // interface datosOperations
